### ISSUE TITLE
rev_B - topherlings

### ISSUE THREAD

**Issue by mffoley** [wzhou2/No-Face#9]
The aim of creating a map to show population over time is clear and seems very interesting. We were wondering what will be displayed on the big map vs what will be displayed when a certain country is clicked.

**Comment by puneetjohal** [comment]
When we click on the country, it will be highlighted a different color and the slider that allows you to pick a year will pop up on the top, as well as the population for the selected year and a line graph that shows all the population data for that country. We will change our sketch to reflect this.
